### ISSUE TITLE
Not able to capture har traffic

### ISSUE THREAD

**Issue by rarunp04** [larsthorup/node-request-har-capture#3]
Hi @larsthorup ,

I am using protractor for my selenium automation and want to capture the browser network data as har file , so was using this module for my use case but having some issue , its not capturing the har file entries and data is empty.

Used Protractor to launch url in chrome browser
and called     request.saveHar('traffic.har');

But the har is doesnt include the entries , can you please guide me if missing anything

![image](https://user-images.githubusercontent.com/44132688/82699718-c7d0ef00-9c8a-11ea-9ab0-75b26a73e3a8.png)

**Comment by larsthorup** [comment]
When you say "Selenium" and "Protractor", I assume that your tests are front-end tests, which run in a browser? Then you cannot use this module, as it runs in Node.js and should be used for "capturing all test traffic from your back-end test suite".

Referring to the 3rd illustration in this blog post: http://www.zealake.com/2015/01/05/unit-test-your-service-integration-layer/ I believe your tests corresponds to the "test" box on the right (testing the client) where this module is used in the "test" box on the left to capture traffic for later use in the front-end tests.

A modern alternative to this module is Polly.js: https://netflix.github.io/pollyjs/#/README
